# Generated by Django 6.0.1 on 2026-01-10 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_category_quiz_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='level',
            field=models.CharField(default='Medium', max_length=20),
        ),
    ]
